apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: msr104payment-msr-deployment
  labels:
   app: msr104payment-sagmsr
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: msr104payment-sagmsr
  template: # create pods using pod definition in this template
    metadata:
        labels:
          app: msr104payment-sagmsr
    spec:
      containers:
      - name: msr104payment
        image: falanta/msr104payment:latest
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 5555
      imagePullSecrets:
        - name: acctest
---
kind: Service
apiVersion: v1	
metadata:
  name: msr104payment-sagmsr-service
spec:
  type: LoadBalancer
  selector:
    app: msr104payment-sagmsr
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5555
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: msr104payment-sagmsr-service
spec:	
  rules:
  - host: msr104payment.daeipresal40399.eur.ad.sag
    http:
      paths:
      - backend:
          serviceName: msr104payment-sagmsr-service
          servicePort: 5555
        path: /
  tls:
  - hosts:
    - msr104payment.daeipresal40399.eur.ad.sag
    secretName: daeipresal40399
